name: Trigger auto deployment for demo-gen-cont

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-gen-cont-AutoDeployTrigger-ab732480-cea8-499d-82e1-e7332e2152b2.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOGENCONT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.DEMOGENCONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOGENCONT_REGISTRY_PASSWORD }}
          containerAppName: demo-gen-cont
          resourceGroup: duke-llm-course
          imageToBuild: ghcr.io/demo-gen-cont:${{ github.sha }}
          
            

     

